export interface RiskReward {
  entry?: number,
  stop?: number,
  target?: number,
  toWinEntry?: number,
  toWinStop?: number,
  toWinTarget?: number,
  monetaryStop?: number,
  monetaryTarget?: number,
  toEntryBank?: number,
  toEntryLiability?:number,
  toEntryStake?: number,
  toStopBank?: number,
  toStopLiability?:number,
  toStopStake?: number,
  toTargetBank?: number,
  toTargetLiability?:number,
  toTargetStake?: number,
  winBack?: number,
  winLay?: number,
  net?: number,
  commission?: number,
  isBackBefore?: boolean,
  isValid?: boolean,
  rating?: number,
  commissionPaid: number
}
